---
apiVersion: osm.io/v1alpha1
kind: ClusterClaim
metadata:
  name: dev-team
  namespace: osm
  labels:
    cluster-owner: tataelxsi
spec:
  id: dev-team
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    version: "1.29"
    minNodeCount: 1
