---
apiVersion: osm.io/v1alpha1
kind: ClusterClaim
metadata:
  name: osm
  namespace: osm
  labels:
    cluster-owner: tataelxsi
spec:
  id: osm
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    version: "1.29"
    minNodeCount: 1
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: crossplane-cluster-connection-secret
