---
apiVersion: osm.io/v1alpha1
kind: ClusterClaim
metadata:
  name: osm-cluster
  namespace: osm
  labels:
    cluster-owner: tataelxsi
spec:
  id: osm-cluster
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    version: "1.29"
    minNodeCount: 1
