---
apiVersion: xcloud.io/v1alpha1
kind: ClusterClaim
metadata:
  name: NAME
  labels:
    cluster-owner: utkarsh
spec:
  id: NAME
  compositionSelector:
    matchLabels:
      provider: PROVIDER
      cluster: CLUSTER
  parameters:
    region: REGION
    nodeSize: SIZE
    version: VERSION
    minNodeCount: 1
