configs:
  secret:
    argocdServerAdminPassword: "$2a$12$KrQXTRm1uBUnvogRe0ABrOi/4NAOBoSKZHSqTu5DX2aSbJ/Nbgnli"
    argocdServerAdminPasswordMtime: "2021-11-08T15:04:05Z"
  cm:
    application.resourceTrackingMethod: annotation
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.212.2.246.1.nip.io
